language: c
sudo: false
addons:
  apt:
    packages:
      - p7zip-full
script:
- bash download.sh
- travis_wait bash prepare.sh
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH}
  file:
    - texlive.tar.xz
  skip_cleanup: true
