language: c
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - p7zip-full
script:
- bash download.sh
- travis-wait.sh bash prepare.sh
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH}
  file:
    - texlive.tar.xz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
